name: Publish RTX Mod

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        
    - name: Make gradle wrapper executable
      run: chmod +x ./gradlew
      
    - name: Build mod
      run: ./gradlew build --no-daemon
      
    - name: Get version and changelog
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        
        # Extract changelog from release
        CHANGELOG=$(cat << 'EOF'
        ${{ github.event.release.body }}
        EOF
        )
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Publish to CurseForge
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        curseforge-id: YOUR_CURSEFORGE_PROJECT_ID  # Replace with your actual project ID
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        
        files: build/libs/*.jar
        name: RTX Mod ${{ steps.version.outputs.VERSION }}
        version: ${{ steps.version.outputs.VERSION }}
        changelog: ${{ steps.version.outputs.CHANGELOG }}
        
        game-versions: |
          1.20.4
        loaders: |
          fabric
        
        dependencies: |
          fabric-api(required){modrinth:P7dR8mSH}{curseforge:306612}
          modmenu(optional){modrinth:mOgUt4GM}{curseforge:308702}
          
    - name: Publish to Modrinth
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: YOUR_MODRINTH_PROJECT_ID  # Replace with your actual project ID
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        
        files: build/libs/*.jar
        name: RTX Mod ${{ steps.version.outputs.VERSION }}
        version: ${{ steps.version.outputs.VERSION }}
        changelog: ${{ steps.version.outputs.CHANGELOG }}
        
        game-versions: |
          1.20.4
        loaders: |
          fabric
        
        dependencies: |
          fabric-api(required){modrinth:P7dR8mSH}{curseforge:306612}
          modmenu(optional){modrinth:mOgUt4GM}{curseforge:308702}
          
    - name: Publish to GitHub Packages
      run: ./gradlew publishAllPublicationsToGitHubPackagesRepository --no-daemon
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  notify-discord:
    runs-on: ubuntu-latest
    needs: publish
    if: success()
    
    steps:
    - name: Discord Webhook Notify
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        content: |
          🚀 **RTX Mod ${{ github.event.release.tag_name }}** has been released!
          
          📦 **Download:** ${{ github.event.release.html_url }}
          📝 **Changelog:** 
          ${{ github.event.release.body }}
          
          Available on CurseForge and Modrinth!
